name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable Nix Flakes
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Lint Nix files
        run: nix develop --command just lint

  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable Nix Flakes
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build package
        run: nix develop --command just build
      - name: Run tests
        run: nix develop --command just test
      - name: Show flake info
        run: nix develop --command just info
